### ISSUE TITLE
Implement initial subset of instructions

### ISSUE THREAD

**Issue by ncatelli** [ncatelli/mainspring#15]
To start testing, I only need an initial subset of instructions most notably

- [x] CMP: for `compare` #83 
- [x] BEQ: for `branch equal` #93 
- [x] BNE: for `branch not eq` #87 
- [x] PHA: for `push A` #43 
- [x] PLA: for `pop A` #44 
- [x] LDA: for `load a` #38 
- [x] STA: for `store a` #39 
- [x] JMP: for `jump` #37  
- [x] NOP: for `no operation`

This should be enough to test basic functionality before starting further implementation work.

**Comment by ncatelli** [comment]
NOP implemented in #17

**Comment by ncatelli** [comment]
All instructions have been implemented
